# Point.py

from numpy import inf, norm


class Point:
    """Class describing single point on the heightmap."""

    def __init__(self, height, x, y, path):
        """Initialization method"""
        self.h = height  # height, generated by DSA
        self.d = inf  # distance from the startpoint, set to infinity as per DA
        self.pos = (x, y)  # position vector
        self.path = path  # path to the point, initialized empty
        self.visited = False  # check if point was visited by DA yet

    def dist(self, other):
        """Method calculating distance between two others given poth points."""

        return norm([self.pos[0] - other.pos[0],
                     self.pos[1] - other.pos[1],
                     self.h - other.h])
